# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Miles/Desktop/Interface Technology Lab/lab_src/rtl_src/rtl_src/liteDRAM.xdc

# XDC: C:/Users/Miles/Desktop/Interface Technology Lab/lab_src/rtl_src/rtl_src/rvfpga.xdc

# Block Designs: bd/swerv_soc/swerv_soc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc || ORIG_REF_NAME==swerv_soc} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_swerv_wrapper_verilog_0_0/swerv_soc_swerv_wrapper_verilog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==swerv_soc_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_axi2wb_intcon_wrapper_0_0/swerv_soc_axi2wb_intcon_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc_axi2wb_intcon_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_axi2wb_intcon_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_wb_gpio_wrapper_0_0/swerv_soc_wb_gpio_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc_wb_gpio_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_wb_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_bootrom_wrapper_0_0/swerv_soc_bootrom_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc_bootrom_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/swerv_soc/ip/swerv_soc_syscon_wrapper_0_0/swerv_soc_syscon_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==swerv_soc_syscon_wrapper_0_0 || ORIG_REF_NAME==swerv_soc_syscon_wrapper_0_0} -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface Technology Lab/lab1/project_2.gen/sources_1/bd/swerv_soc/swerv_soc_ooc.xdc
